# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-added-large-files
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: end-of-file-fixer
            types: [file, python]

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            # max-line-length setting is the same as black
            # commit cannot be done when cyclomatic complexity is more than 10.
            args:
                [
                    --max-line-length,
                    "88",
                    --ignore=E402,
                    --max-complexity,
                    "10",
                    --max-expression-complexity=7,
                    --max-cognitive-complexity=7,
                ]
            additional_dependencies:
                [
                    flake8-bugbear,
                    flake8-builtins,
                    flake8-eradicate,
                    pep8-naming,
                    flake8-expression-complexity,
                    flake8-cognitive-complexity,
                ]
            types: [file, python]
            exclude: 'catr.*$'

    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
          - id: black
            language_version: python3
            types: [file, python]

    - repo: https://github.com/pycqa/isort
      rev: 5.9.3
      hooks:
          - id: isort
            args: ["--profile", "black"]
            types: [file, python]

    # for docstrings in python codes
    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place]
            types: [file, python]
